package(
    default_visibility = ["//:__subpackages__"],
)

filegroup(
    name = "machine_translation",
    srcs = ["machine_translation.prototext"],
)

filegroup(
    name = "vae",
    srcs = ["vae.prototext"],
)

filegroup(
    name = "vit",
    srcs = ["vit.prototext"],
)
