package(
    default_visibility = ["//:__subpackages__"],
)

filegroup(
    name = "imagenette",
    srcs = glob([
        "imagenette/**",
    ]),
)

filegroup(
    name = "mnist",
    srcs = glob([
        "mnist/**",
    ]),
)

filegroup(
    name = "ted_hrlr_translate_pt_en_converter",
    srcs = glob([
        "ted_hrlr_translate_pt_en_converter/**",
    ]),
)

filegroup(
    name = "ted_hrlr_translate",
    srcs = glob([
        "ted_hrlr_translate/**",
    ]),
)
